name: GitHub Actions Maven build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Verify MySQL connection from container 
      uses: shogo82148/actions-setup-mysql@v1.3.0
      with:
        mysql-version: '8.0'
        auto-start: true
        root-password: ${{ secrets.MYSQL }}
    - name: create image database
      run: mysql -h 127.0.0.1 -P 3306 -uroot -p${{ secrets.MYSQL }} -e 'CREATE DATABASE image;'
    - name: show databases
      run: mysql -h 127.0.0.1 -P 3306 -uroot -p${{ secrets.MYSQL }} -e 'SHOW DATABASES;'
    - name: find users
      run: mysql -h 127.0.0.1 -P 3306 -uroot -p${{ secrets.MYSQL }} -e 'use mysql; select user,host from user;'
    - name: setup user
      run: mysql -h 127.0.0.1 -P 3306 -uroot -p${{ secrets.MYSQL }} -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ secrets.MYSQL }}';"
    - name: flush privileges
      run: mysql -h 127.0.0.1 -P 3306 -uroot -p${{ secrets.MYSQL }} -e 'FLUSH PRIVILEGES;'
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2
    - name: Step 2 - Setup JDK 17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Step 3 - Build Maven project
      env: # lookup key as an environment variable
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        MYSQL: ${{ secrets. MYSQL }}
      run: mvn --batch-mode verify --file pom.xml
    - name: Step 4 - List the root directory
      run: ls -a
    - name: Step 5 - List the target directory
      run: |
        cd target
        ls -a
